version: '3.9'

services:

  application:
    container_name: goexpert-cloudrun
    build:
      context: .
      dockerfile: Dockerfile
    image: goexpert-cloudrun:latest
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - WEB_SERVER_PORT=8080
      - WEATHERAPI_KEY=

networks:
  app_network:
    driver: bridge